version: "3.8"

services:
    webapp:
        container_name: "webapp"

        build: 
            context: .
            dockerfile: Dockerfile

        volumes: 
            - ./services/webapp:/var/www:rw

        ports:  
            - 80:80
    
        restart: always
        