version: "3.8"

services:
    webapp:
        container_name: "webapp"

        build: 
            context: .
            dockerfile: Dockerfile
            args:
                PASSWD: ${PASSWD}
        
        env_file:
            - .env

        volumes: 
            - ./services/webapp:/var/www:rw

        ports:  
            - 80:80
    
        restart: always
        